# Generated by Django 2.2.7 on 2022-11-07 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20221103_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default=30, height_field=30, upload_to='profile', verbose_name='الصورة الشخصية', width_field=30),
            preserve_default=False,
        ),
    ]
