# Generated by Django 2.2.7 on 2022-11-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20221112_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='join_us',
            field=models.DateTimeField(auto_now_add=True, default=1, verbose_name='وقت الانضمام'),
            preserve_default=False,
        ),
    ]
