# Generated by Django 2.2.7 on 2022-11-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20221121_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='join_new',
            field=models.DateTimeField(default='', verbose_name='وقت الانضمام'),
        ),
    ]
