# Generated by Django 2.2.7 on 2022-11-21 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20221121_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='join_new',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='وقت الانضمام'),
        ),
    ]
