# Generated by Django 2.2.7 on 2022-11-21 14:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20221121_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='join_new',
        ),
        migrations.AddField(
            model_name='profile',
            name='join_us',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='وقت الانضمام'),
            preserve_default=False,
        ),
    ]
