# Generated by Django 2.2.7 on 2022-11-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20221121_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='join_us',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت الانضمام'),
        ),
    ]
