# Generated by Django 2.2.7 on 2022-11-21 14:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20221121_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='join_us',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='وقت الانضمام'),
            preserve_default=False,
        ),
    ]
