# Generated by Django 2.2.7 on 2022-11-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20221121_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='join_us',
            field=models.DateTimeField(null=True, verbose_name='وقت الانضمام'),
        ),
    ]
