# Generated by Django 2.2.7 on 2022-11-21 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20221121_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='start_date',
        ),
    ]
