# Generated by Django 2.2.7 on 2022-11-21 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20221121_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='join_us',
            new_name='join_new',
        ),
    ]
