# Generated by Django 2.2.7 on 2022-11-22 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20221122_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='join_new',
            field=models.DateField(default=1, verbose_name='وقت الانضمام:'),
            preserve_default=False,
        ),
    ]
