# Generated by Django 2.2.7 on 2022-11-22 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20221123_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='join_new',
            field=models.TimeField(blank=True, null=True, verbose_name='وقت الانضمام:'),
        ),
    ]
