# Generated by Django 2.2.7 on 2022-11-22 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20221123_0105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='join_new',
        ),
        migrations.AddField(
            model_name='profile',
            name='fieldName',
            field=models.TimeField(default=1),
            preserve_default=False,
        ),
    ]
