# Generated by Django 2.2.7 on 2022-11-22 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_auto_20221123_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fieldName',
            field=models.TimeField(null=True),
        ),
    ]
