# Generated by Django 2.2.7 on 2022-11-22 23:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_auto_20221123_0110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='time',
        ),
        migrations.AddField(
            model_name='profile',
            name='join_new',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 23, 1, 11, 30, 929564)),
        ),
    ]
